name: Scrape Athletes FIE Rankings Data

on:
  schedule:
    - cron: "0 5 * * 2" # 5am every Tuesday

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas fpdf lxml

    - name: Run scrape script
      run: python webscrape_json.py  # Replace with the actual script name

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Ranking_data.csv Ranking_PDF_reports/Fencing_Ranking_Report_*.pdf
        git commit -m 'Add scraped ranking data and PDF report'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

